server:
  port: 8091


spring:
  datasource:
#    url: jdbc:postgresql://localhost:5434/postgres
#    username: postgres
#    password: postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        default_schema: musicshop
        generate_statistics: true
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  main:
    allow-circular-references: true

app:
  jwt:
    secret: "Olol630000006A586E3272357538782F413F4428472B4B6250645367566BIviv"
    expiration: 86400000

  configuration:
    cors:
      origins: 'http://localhost:8080'
      methods: '*'
      headers: '*'
      allow-credentials: true
    threadPoolTaskExecutor:
      corePoolSize: 50
      maxPoolSize: 50






