server:
  port: 9091

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/ms
    username: mssu
    password: mssupass
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
      show-sql: true
      dialect: PostgreSQLDialect

  flyway:
    baseline-on-migrate: true
token:
  signing:
    key: 5E6TYE5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75345875
#  liquibase:
#    enabled: true
#    change-log: classpath:db/changelog/db.changelog-master.yaml

  main:
    allow-circular-references: true

#app:
#  jwt:
#    secret: "Olol630000006A586E3272357538782F413F4428472B4B6250645367566BIviv"
#    expiration: 86400000

  configuration:
    cors:
      origins: 'http://localhost:9091'
      methods: '*'
      headers: '*'
      allow-credentials: true
    threadPoolTaskExecutor:
      corePoolSize: 50
      maxPoolSize: 50






